name: spark
description: "A habit tracking app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  postgres: ^3.2.1
  collection: 1.18.0  
  google_fonts: ^6.2.1
  intl: ^0.17.0
  flutter_calendar_carousel: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/